import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { svrAxios } from "@/api/svr-axios";
import { apiUrl } from "@/paths";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { data } = await svrAxios().get(apiUrl.users.currentUser);

  console.log('root read');

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header currentUser={data.currentUser} />
        {children}
      </body>
    </html>
  );
}
